mySite/contact/models.py
from datetime import datetime
from socket import inet_ntoa


class Contact:

    def __init__(self, name, email, message, ip):
        self._id = datetime.now().strftime("%Y%m%d-%H%M%S-%f")
        self.name = name
        self.email = email
        self.message = message
        self.ip = ip

    def __repr__(self):
        return self._id + '\n' + self.name + '\n' + self.email + '\n' + self.message + '\n' + \
               inet_ntoa(self.ip.to_bytes(4, byteorder='little', signed=False))

mySite/contact/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, validators


class ContactForm(FlaskForm):
    name = StringField('Name', [validators.required(), validators.length(max=100)])
    email = StringField('Email', [validators.required(), validators.length(max=100)])
    message = TextAreaField('Message (500 Character Limit)', [validators.required(), validators.length(max=500)])

mySite/__init__.py
from flask import Flask
from flask_mail import Mail

from config import mail_settings, ProductionConfig

mail = Mail()


def create_app():
    app = Flask(__name__)
    app.config.from_object(ProductionConfig)
    app.config.update(mail_settings)

    mail.init_app(app)

    from mySite import contact
    from mySite import blog
    from mySite import site

    app.register_blueprint(contact.bp)
    app.register_blueprint(blog.bp)
    app.register_blueprint(site.bp)

    # make "index" point at "/", which is handled by "site.home"
    app.add_url_rule("/", endpoint="site.home")

    return app

mySite/blog/__init__.py
from .views import bp

mySite/blog/views.py
from flask import render_template, Blueprint

bp = Blueprint("blog", __name__)


@bp.route('/blog')
def blog():
    return render_template('blog/blog.html')

mySite/contact/__init__.py
from .views import bp

mySite/contact/views.py
import os
import re
from socket import inet_aton

from flask import request, redirect, render_template, flash, url_for, Blueprint, current_app
from flask_mail import Message
import logging
from logging.config import dictConfig

from .dao import MessageStore
from .forms import ContactForm
from .models import Contact

from mySite import mail

bp = Blueprint('contact', __name__)


@bp.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm()
    if request.method == 'POST':
        db_server = current_app.config['COUCHDB_SERVER']
        db_name = current_app.config['COUCHDB_DATABASE']
        dictConfig(current_app.config['LOGGING_CONFIG'])
        logger = logging.getLogger()

        if not re.search(r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)', form.email.data):
            flash('You must enter a valid email')
            return redirect(url_for('contact.contact'))
        elif not form.validate():
            flash('Character limit Exceeded')
        else:
            msg = Message(subject='New message from: ' + form.name.data,
                          sender=os.getenv('EMAIL_USERNAME'),
                          recipients=[os.getenv('MY_EMAIL')],
                          body='Message From: ' + form.name.data + ' \nReply Email: ' + form.email.data +
                               '\nMessage: ' + form.message.data)

            headers_list = request.headers.getlist('X-Forwarded-For')
            user_ip = headers_list[0] if headers_list else request.remote_addr
            coded_ip = int.from_bytes(inet_aton(user_ip), byteorder='little', signed=False)

            try:
                document = Contact(name=form.name.data, email=form.email.data, message=form.message.data, ip=coded_ip)
                logger.info(document)
                couch = MessageStore(db_server, db_name)
                couch.add_msg(document)
                mail.send(msg)
            except Exception as e:
                logger.error(e)
                return render_template('contact/test.html', title='Try again later.', message='Something went wrong.'
                                                                                              ' Failure logged.')
            return render_template('contact/test.html', title='Message Sent', message='Success! Thanks for coming.')
    return render_template('contact/contact.html', form=form)


@bp.route('/test', methods=['GET'])
def test():
    return render_template('contact/test.html', title='Congrats', message='You found the test page.')

mySite/site/__init__.py
from .views import bp

mySite/site/views.py
from flask import render_template, Blueprint

bp = Blueprint("site", __name__)


@bp.route('/')
def home():
    return render_template('site/home.html')


@bp.route('/about')
def about():
    return render_template('site/about.html')


@bp.route('/portfolio')
def portfolio():
    return render_template('site/portfolio.html')

mySite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="{{ url_for('static', filename='icons/MH_Logo1.ico') }}" rel="cloud icon">
    {% block header %}{% endblock %}
</head>
<body class="bg-dark text-white">

<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<div class="header">
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top" role="navigation"
         style="background-color: rgba(47,47,47,0.87);">
        <a class="navbar-brand" href="{{ url_for('site.home') }}">Homepage</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.about') }}">About Me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('site.portfolio') }}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.blog') }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('contact.contact') }}">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
</div>
<br/><br/><br/>
{% block content %}{% endblock %}
{% block scripts %}{% endblock %}
</body>
</html>

mySite/templates/blog/blog.html
{% extends 'base.html' %}
{% block title %} Blog {% endblock %}
{% block content %}
<h2 align="center">This Blog is a Work in Progress</h2>

<div id="albumRecommendations" class="tabcontent text-center">
    <h3>For now here are some of my favorite songs:</h3>
    <ul>
        <li>Post Animal: Special Moment (2018)</li>
        <br/>
        <iframe src="https://open.spotify.com/embed/track/3Z8804glpo31YP2aPn7w28" width="300" height="380"
                frameborder="0"
                allowtransparency="true" allow="encrypted-media"></iframe>
    </ul>
    <ul>
        <li> Tame Impala: Feels Like We Only Go Backwards (2012)</li>
        <br/>
        <iframe src="https://open.spotify.com/embed/track/0LtOwyZoSNZKJWHqjzADpW" width="300" height="380"
                frameborder="0"
                allowtransparency="true" allow="encrypted-media"></iframe>
    </ul>
    <ul>
        <li>King Gizzard and the Lizard Wizard: I'm in Your Mind (2014)</li>
        <br/>
        <iframe src="https://open.spotify.com/embed/track/7Jt8XwrIn68jXTwX22VDvX" width="300" height="380"
                frameborder="0"
                allowtransparency="true" allow="encrypted-media"></iframe>
    </ul>
</div>
{% endblock %}

mySite/templates/contact/contact.html
{% extends "base.html" %}
{% block title %} Contact Me {% endblock %}
{% block content %}
<div class="text-center">
    <h2><b>Send me a message or just say hi:</b></h2><br/><br/>
</div>
<div class="container" style="min-height:100%; width:80%">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">×</span></button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
<div class="form text-center">
    <form method="POST" action="">
        {{ form.csrf_token }}
        {{ form.name.label }}<br/> {{ form.name(size=20) }}<br/>
        {{ form.email.label }}<br/> {{ form.email(size=20) }}<br/>
        {{ form.message.label }}<br/> {{ form.message(cols="20", rows="10") }} <br/>
        {# {{ form.captcha }} #}
        <input type="submit" value="Go">
    </form>
</div>
{% endblock %}

mySite/templates/contact/test.html
{% extends "base.html" %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<div class="text-center">
    <h1>{{ message }}</h1>
</div>
{% endblock %}

mySite/templates/site/home.html
{% extends 'base.html' %}
{% block title %} Mitchell Henschel's Homepage {% endblock %}
{% block header %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/open-iconic-bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/animate.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/aos.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/dots.css') }}">
{% endblock %}

{% block content %}

<div class="container">
    <section class="home-slider owl-carousel js-fullheight">
        <div class="slider-item js-fullheight">
            <div class="container">
                <div class="row slider-text align-items-center text-center justify-content-center"
                     data-scrollax-parent="true">
                    <div class="col-md-12 ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
                        <p><a href="#" class="scroll">Hello! My name is</a></p>
                        <h1 class="mb-3" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Mitchell
                            Henschel</h1>
                    </div>
                </div>
            </div>
        </div>

        <div class="slider-item js-fullheight">
            <div class="overlay"></div>
            <div class="container">
                <div class="row slider-text align-items-center text-center justify-content-center"
                     data-scrollax-parent="true">
                    <div class="col-md-12 ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
                        <p><a href="#" class="scroll">Eastern Michigan University Graduate</a></p>
                        <h1 class="mb-3" data-scrollax="properties: {translateY: '30%', opacity: 1.6}">Full Stack Data
                            Scientist</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Create Background Pattern -->
    <canvas id="animation-pattern"></canvas>
    <!-- Create Background Dots -->
    <canvas id="animation-dots"></canvas>
</div>
<footer class="footer font-small text-center"
        style="position: fixed; width: 100%; background-color: black; text-align: center; padding-top: 10px; padding-bottom: 20px; bottom: 0;">
    <div class="container">
        <ul class="list-unstyled list-inline text-center" style="display: inline;">
            <li class="list-inline-item">
                Homepage inspired by<a href="https://codepen.io/dreammmr/pen/ejrjBv"> Codepen Electric Tails</a>
            </li>
        </ul>
    </div>
</footer>
{% endblock %}
{% block scripts %}
<script src="static/js/animate-dots.js"></script>
<script src="static/js/jquery.min.js"></script>
<script src="static/js/jquery.magnific-popup.min.js"></script>
<script src="static/js/bootstrap.min.js"></script>
<script src="static/js/jquery-migrate-3.0.1.min.js"></script>
<script src="static/js/jquery.easing.1.3.js"></script>
<script src="static/js/jquery.waypoints.min.js"></script>
<script src="static/js/jquery.stellar.min.js"></script>
<script src="static/js/owl.carousel.min.js"></script>
<script src="static/js/aos.js"></script>
<script src="static/js/jquery.animateNumber.min.js"></script>
<script src="static/js/scrollax.min.js"></script>
<script src="static/js/main.js"></script>
{% endblock %}

mySite/templates/site/portfolio.html
{% extends 'base.html' %}
{% block title %} Portfolio {% endblock %}
{% block header %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">
{% endblock %}
<!--Cards-->
{% block content %}
<div class="card-deck bg-secondary">
    <!--Row1-->
    <div class="row mx-auto" style="margin-top:5px;margin-bottom: 5px;">
        <!--MySite-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top" src="static/images/cloud.png" alt="Sample" style="width:7rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">This Website</h5>
                <p class="card-text text-center">A personal project to hold my portfolio</p>
                <button id="btn_1" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_1').style.display = 'block';">Details
                </button>
            </div>
        </div>
        <!--WEMU-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top" src="static/images/WEMU-Logo.png" alt="Sample"
                 style="width:5rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">WEMU Music Catalog</h5>
                <p class="card-text text-center">Django CRUD web app with MySQL</p>
                <button id="btn_2" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_2').style.display = 'block';">Details
                </button>
            </div>
        </div>
    </div>
    <!--Row2-->
    <div class="row mx-auto" style="margin-top:5px;margin-bottom: 5px;">
        <!--Client Server-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top" src="static/images/network.png" alt="Sample" style="width:7rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">Stock Trading Client-Server Program</h5>
                <p class="card-text text-center">Socket programming in C</p>
                <button id="btn_3" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_3').style.display = 'block';">Details
                </button>
            </div>
        </div>
        <!--Project3-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top " src="static/images/dos.png " alt="Sample" style="width:5rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">DOS-Like Operating System</h5>
                <p class="card-text text-center">A low-level OS using assembly</p>
                <button id="btn_4" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_4').style.display = 'block';">Details
                </button>
            </div>
        </div>
    </div>
    <!--Row3-->
    <div class="row mx-auto" style="margin-top:5px;margin-bottom: 5px;">
        <!--Bash Script-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top" src="static/images/Terminal-512.png" alt="Sample"
                 style="width:5rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">Bash Document Sorting</h5>
                <p class="card-text text-center">A script I use for my desktop</p>
                <button id="btn_5" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_5').style.display = 'block';">Details
                </button>
            </div>
        </div>
        <!--Project6-->
        <div class="card align-items-center bg-dark" style="width: 30rem">
            <img class="card-img-top " src="static/images/twitter_icon.png " alt="Sample"
                 style="width:5rem;height:5rem;">
            <div class="card-body col text-center">
                <h5 class="card-title">Twitter Sentiment Analysis</h5>
                <p class="card-text text-center">Input a topic to find the sentiment of it on Twitter</p>
                <button id="btn_6" class="btn btn-info btn-primary"
                        onclick="getElementById('modal_6').style.display = 'block';">Details
                </button>
            </div>
        </div>
    </div>
</div>
<!-- Modal 1 -->
<div id="modal_1" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">This Site!</h4>
            <span class="close" onclick="getElementById('modal_1').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: Python Flask, HTML, CSS, Javascript</p>
            <p>Description: A side project to use as my personal portfolio! It took a few weekends to build, and
                is hosted from PythonAnywhere.com. <br/>In the works: A blog page that will use CouchDB to hold
                posts..</p>
            <p align="center"><a href="https://github.com/Elkip/mySite">View Repository</a></p>
        </div>
    </div>
</div>
<!-- Modal 2 -->
<div id="modal_2" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">WEMU Music Catalog</h4>
            <span class="close" onclick="getElementById('modal_2').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: Python Django, HTML, CSS, JavaScript, SQL, Bash</p>
            <p>Description: My Undergraduate project I worked on for 2 semesters. Contained in an Amazon EC2
                instance, it has a django app connected to a MySQL database. Allows for search, input and deletion
                of music in the catalog. The first half of the project I exported the data from MS Access and
                designed the relational database with ER diagrams. In the second half of the project, I led a team
                of 4 students in
                building the web application using the Django frameworks.</p>
            <p align="center"><a href="https://github.com/Elkip/WEMU_App">View Repository</a></p>
        </div>
    </div>
</div>
<!-- Modal 3 -->
<div id="modal_3" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Client-Server Stock Trading Program</h4>
            <span class="close" onclick="getElementById('modal_3').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: C, Makefile</p>
            <p>Description: A project I created for a Networking class I took. Select a stock and quantity and send
                the
                order through UDP and TCP connections with an RSA encryption scheme. See the readme on how to start
                the server and key manager.</p>
            <p align="center"><a href="https://github.com/Elkip/Networking_Prinipals">View Repository</a></p>
        </div>
    </div>
</div>
<!-- Modal 4 -->
<div id="modal_4" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">DOS-Like Operating System</h4>
            <span class="close" onclick="getElementById('modal_4').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: NASM Assembly</p>
            <p>Description: Created for a class on the conceptual workings of operating systems. Implemented a
                low-level
                operating system using x86 instructions and BIOS calls.</p>
            <p align="center"><a href="https://github.com/Elkip/OS_assembly">View Repository</a></p>
        </div>
    </div>
</div>
<!-- Modal 5 -->
<div id="modal_5" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Document Sorting Bash Script</h4>
            <span class="close" onclick="getElementById('modal_5').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: Bash</p>
            <p>Description: If your're like me, you might have a Desktop or Downloads folder full of various files
                that may or may not be important. This script is designed to sort those files based on their
                extension.
                It runs at startup via cron. It could easily be adapted to Windows Powershell.</p>
            <p align="center"><a href="https://github.com/Elkip/clean_downloads">View Repository</a></p>
        </div>
    </div>
</div>
<!-- Modal 6 -->
<div id="modal_6" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Twitter Sentiment Analysis</h4>
            <span class="close" onclick="getElementById('modal_6').style.display='none';">&times;</span>
        </div>
        <div class="modal-body">
            <p>Languages: Python</p>
            <p>Description: Uses Text-Blob to find if a word is positive or negative and Twitter-Scraper to get the
                tweets pertaining to a topic without having to provide log-in credentials or an API key.</p>
            <p align="center"><a href="https://github.com/Elkip/Tweet_Sentiment">View Repository</a></p>
        </div>
    </div>
</div>
<script>
    // Get the modal
    var modals = [];
    modals.push(document.getElementById("modal_1"));
    modals.push(document.getElementById("modal_2"));
    modals.push(document.getElementById("modal_3"));
    modals.push(document.getElementById("modal_4"));
    modals.push(document.getElementById("modal_5"));
    modals.push(document.getElementById("modal_6"));
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (modals.includes(event.target)) {
            (event.target).style.display = "none";
        }
    }
</script>

{% endblock %}